name:                term-rewriter
version:             0.1.0.0
github:              "githubuser/term-rewriter"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/term-rewriter#readme>

dependencies:
- base >= 4.7 && < 5
- hspec >= 2.7.8
- QuickCheck >= 2.14.2
- mtl >= 2.2.2 

library:
  source-dirs: src

executables:
  term-rewriter-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - term-rewriter

tests:
  Term-Parser-Tests:
    main:                Terms.TermParserSpec
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - term-rewriter
  Basic-Unification-Tests:
    main:               Unification.UnificationSpec
    source-dirs:        test 
    ghc-options: 
    - -threaded
    - -rtsopts 
    - -with-rtsopts=-N
    dependencies: 
      - term-rewriter 
  Rewrite-Tests:
    main:               TermRewriting.RewriteSpec
    source-dirs:        test 
    ghc-options: 
    - -threaded
    - -rtsopts 
    - -with-rtsopts=-N
    dependencies: 
      - term-rewriter 
  PolyOrders-Tests:
    main:              Orders.PolyOrdersSpec
    source-dirs:       test 
    gch-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - term-rewriter
  TermOrders-Tests:
    main:              Orders.TermOrdersSpec
    source-dirs:       test 
    gch-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - term-rewriter
  MonadicTermOrders-Tests:
    main:              Orders.MonadicTermOrdersSpec
    source-dirs:       test 
    gch-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - term-rewriter

