name:                term-rewriter
version:             0.1.0.0
github:              "diiStephen/term-rewriter"
license:             BSD3
author:              "Daniel S. Hono II"
maintainer:          ""
copyright:           "2021 Daniel S. Hono II"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/term-rewriter#readme>

dependencies:
- base >= 4.7 && < 5
- hspec >= 2.7.8
- QuickCheck >= 2.14.2
- mtl >= 2.2.2
- containers
- hspec-discover

library:
  source-dirs: src

executables:
  term-rewriter-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - term-rewriter

tests:
  unit-tests:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - term-rewriter
      - hspec-discover